### ISSUE TITLE
您好，我在wilderface上测试时hard结果是67左右，请问是测试哪里有问题吗

### ISSUE THREAD

**Issue by yjhuasheng** [ouyanghuiyu/darknet_face_with_landmark#12]

**Comment by Ray507** [comment]
我也是 
![predictions](https://user-images.githubusercontent.com/45837161/82968835-c859e480-a000-11ea-8bcf-c0d93b74684e.jpg)

**Comment by DayBreak-u** [comment]
cfg里面网络的尺寸改了吗，640 640对应的是0.71

**Comment by yjhuasheng** [comment]
明白了，我尺寸改的是640x480
