### ISSUE TITLE
hi，我想请问下训练中期会报错吗，我训练中期会突然停止出现下面的错误

### ISSUE THREAD

**Issue by yjhuasheng** [ouyanghuiyu/darknet_face_with_landmark#17]
*** Error in `./darknet': double free or corruption (out): 0x000000005ef54080 ***

**Comment by CangHaiQingYue** [comment]
我也遇到了这个问题，等待中。。。。

**Comment by DayBreak-u** [comment]
我提供了torch的模型训练版本，精度更高，而且更简单：https://github.com/ouyanghuiyu/yolo-face-with-landmark
你们这个错误应该是越界的问题

**Comment by CangHaiQingYue** [comment]
> 我提供了torch的模型训练版本，精度更高，而且更简单：https://github.com/ouyanghuiyu/yolo-face-with-landmark
> 你们这个错误应该是越界的问题

大佬好，torch版本的模型可以转为caffe的么？ 现在的可行路径貌似是torch->onnx->caffe?

**Comment by DayBreak-u** [comment]
@CangHaiQingYue 理论上可以的，但是对应的激活函数要自己实现一下（我是用mbv3，有hsigmode和hswish）

**Comment by DayBreak-u** [comment]
@CangHaiQingYue 先写好对应的deplpy.prototxt 然后权重改成caffe格式应该是可以的

**Comment by CangHaiQingYue** [comment]
> @CangHaiQingYue 理论上可以的，但是对应的激活函数要自己实现一下（我是用mbv3，有hsigmode和hswish）

那就不好落地了，因为硬件一般不支持这些新的层。只能用darkent版本的，因为看到darknet版本的有一个是mbv2，这个里面没有hsigmode和hswish。

**Comment by DayBreak-u** [comment]
@CangHaiQingYue 可以用我的torch版本，你自己加入mbv2自己训练一个模型，很简单的

**Comment by DayBreak-u** [comment]
@CangHaiQingYue 硬件是支持的，这些层的计算也是基于mbv2 的relu6的

**Comment by CangHaiQingYue** [comment]
> @CangHaiQingYue 可以用我的torch版本，你自己加入mbv2自己训练一个模型，很简单的

好的，谢谢大佬 ！

**Comment by CangHaiQingYue** [comment]
> @CangHaiQingYue 硬件是支持的，这些层的计算也是基于mbv2 的relu6的
emmm，大佬有空了的话，可以fix一个这个问题，我目前大致定位在https://github.com/ouyanghuiyu/darknet_face_with_landmark/blob/2db381ee665fd16ae0dda62749e5411523371e97/src/yolo_layer.c#L483

**Comment by Ronales** [comment]
同样遇到这个问题。。。求解决

**Comment by Ronales** [comment]
> > @CangHaiQingYue 硬件是支持的，这些层的计算也是基于mbv2 的relu6的
> > emmm，大佬有空了的话，可以fix一个这个问题，我目前大致定位在https://github.com/ouyanghuiyu/darknet_face_with_landmark/blob/2db381ee665fd16ae0dda62749e5411523371e97/src/yolo_layer.c#L483

请问您后来解决了吗？

**Comment by w840401** [comment]
How did you train successfully?

**Comment by yjhuasheng** [comment]
> How did you train successfully?

只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单

**Comment by w840401** [comment]
> > How did you train successfully?
> 
> 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单

我編譯過了
但是我沒有預訓練檔案來做訓練
官方的是  yolov3 使用的darknet53.conv
這邊是用哪一個呢?

還是你能給我參考你下的 訓練指令?

我必須使用darknet C語言版的  torch測試通過了
萬分感謝 求指教

**Comment by yjhuasheng** [comment]
> > > How did you train successfully?
> > 
> > 
> > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> 
> 我編譯過了
> 但是我沒有預訓練檔案來做訓練
> 官方的是 yolov3 使用的darknet53.conv
> 這邊是用哪一個呢?
> 
> 還是你能給我參考你下的 訓練指令?
> 
> 我必須使用darknet C語言版的 torch測試通過了
> 萬分感謝 求指教

我用的这个，这个模型和网络是我自己魔改的
./darknet detector train ./data/face.data ./cfg/yolov3_face.cfg ./backup/yolov3_face_3000.weights -dont_show

**Comment by w840401** [comment]
> > How did you train successfully?
> 
> 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单

我下的指令是:
./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg darknet53.conv.74

你呢?

**Comment by yjhuasheng** [comment]
> > > How did you train successfully?
> > 
> > 
> > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> 
> 我下的指令是:
> ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg darknet53.conv.74
> 
> 你呢?

额，你用的mbv2的主干网，怎么能用darknet53的做预训练模型呢？

**Comment by w840401** [comment]
> > > > How did you train successfully?
> > > 
> > > 
> > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > 
> > 
> > 我下的指令是:
> > ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg darknet53.conv.74
> > 你呢?
> 
> 额，你用的mbv2的主干网，怎么能用darknet53的做预训练模型呢？

對  我能理解  不過 我不知到哪裡找尋mbv2的 預訓練? 還是直接訓練就好....?

**Comment by yjhuasheng** [comment]
> > > > > How did you train successfully?
> > > > 
> > > > 
> > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > 
> > > 
> > > 我下的指令是:
> > > ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg darknet53.conv.74
> > > 你呢?
> > 
> > 
> > 额，你用的mbv2的主干网，怎么能用darknet53的做预训练模型呢？
> 
> 對 我能理解 不過 我不知到哪裡找尋mbv2的 預訓練? 還是直接訓練就好....?

找不到就重头训练吧，感觉重头训练效果也还可以

**Comment by yjhuasheng** [comment]
> > > > > How did you train successfully?
> > > > 
> > > > 
> > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > 
> > > 
> > > 我下的指令是:
> > > ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg darknet53.conv.74
> > > 你呢?
> > 
> > 
> > 额，你用的mbv2的主干网，怎么能用darknet53的做预训练模型呢？
> 
> 對 我能理解 不過 我不知到哪裡找尋mbv2的 預訓練? 還是直接訓練就好....?

用作者的那个啊，在models里面吧

**Comment by w840401** [comment]
> > > > > > How did you train successfully?
> > > > > 
> > > > > 
> > > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > > 
> > > > 
> > > > 我下的指令是:
> > > > ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg darknet53.conv.74
> > > > 你呢?
> > > 
> > > 
> > > 额，你用的mbv2的主干网，怎么能用darknet53的做预训练模型呢？
> > 
> > 
> > 對 我能理解 不過 我不知到哪裡找尋mbv2的 預訓練? 還是直接訓練就好....?
> 
> 用作者的那个啊，在models里面吧

models 裡面 是完成品的weights吧!!!  訓練完成的

**Comment by yjhuasheng** [comment]
> > > > > > > How did you train successfully?
> > > > > > 
> > > > > > 
> > > > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > > > 
> > > > > 
> > > > > 我下的指令是:
> > > > > ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg darknet53.conv.74
> > > > > 你呢?
> > > > 
> > > > 
> > > > 额，你用的mbv2的主干网，怎么能用darknet53的做预训练模型呢？
> > > 
> > > 
> > > 對 我能理解 不過 我不知到哪裡找尋mbv2的 預訓練? 還是直接訓練就好....?
> > 
> > 
> > 用作者的那个啊，在models里面吧
> 
> models 裡面 是完成品的weights吧!!! 訓練完成的

你要是想重头训练就可以不用，要是想微调就在这个基础上微调，或者你就直接用这个模型不用训练

**Comment by w840401** [comment]
> > > > > > > > How did you train successfully?
> > > > > > > 
> > > > > > > 
> > > > > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > > > > 
> > > > > > 
> > > > > > 我下的指令是:
> > > > > > ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg darknet53.conv.74
> > > > > > 你呢?
> > > > > 
> > > > > 
> > > > > 额，你用的mbv2的主干网，怎么能用darknet53的做预训练模型呢？
> > > > 
> > > > 
> > > > 對 我能理解 不過 我不知到哪裡找尋mbv2的 預訓練? 還是直接訓練就好....?
> > > 
> > > 
> > > 用作者的那个啊，在models里面吧
> > 
> > 
> > models 裡面 是完成品的weights吧!!! 訓練完成的
> 
> 你要是想重头训练就可以不用，要是想微调就在这个基础上微调，或者你就直接用这个模型不用训练

喔喔  所以指令 ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg  
這樣下 就是正確的囉?

**Comment by w840401** [comment]
> > > > How did you train successfully?
> > > 
> > > 
> > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > 
> > 
> > 我編譯過了
> > 但是我沒有預訓練檔案來做訓練
> > 官方的是 yolov3 使用的darknet53.conv
> > 這邊是用哪一個呢?
> > 還是你能給我參考你下的 訓練指令?
> > 我必須使用darknet C語言版的 torch測試通過了
> > 萬分感謝 求指教
> 
> 我用的这个，这个模型和网络是我自己魔改的
> ./darknet detector train ./data/face.data ./cfg/yolov3_face.cfg ./backup/yolov3_face_3000.weights -dont_show

不好意思
您的yolov3_face_3000.weights  是如何得來的呢?
如果是第一次重頭訓練的話

**Comment by yjhuasheng** [comment]
> 果是第一次重頭訓練的話

我自己从头训练的啊，然后中间断了一次，我就在这个模型的基础上继续微调的

**Comment by yjhuasheng** [comment]
> > > > > How did you train successfully?
> > > > 
> > > > 
> > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > 
> > > 
> > > 我編譯過了
> > > 但是我沒有預訓練檔案來做訓練
> > > 官方的是 yolov3 使用的darknet53.conv
> > > 這邊是用哪一個呢?
> > > 還是你能給我參考你下的 訓練指令?
> > > 我必須使用darknet C語言版的 torch測試通過了
> > > 萬分感謝 求指教
> > 
> > 
> > 我用的这个，这个模型和网络是我自己魔改的
> > ./darknet detector train ./data/face.data ./cfg/yolov3_face.cfg ./backup/yolov3_face_3000.weights -dont_show
> 
> 不好意思
> 您的yolov3_face_3000.weights 是如何得來的呢?
> 如果是第一次重頭訓練的話

我记得好像是在作者的model上微调训练的，然后中间中断过，后续就在这个模型的基础上继续训练微调的

**Comment by w840401** [comment]
> > > > > > How did you train successfully?
> > > > > 
> > > > > 
> > > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > > 
> > > > 
> > > > 我編譯過了
> > > > 但是我沒有預訓練檔案來做訓練
> > > > 官方的是 yolov3 使用的darknet53.conv
> > > > 這邊是用哪一個呢?
> > > > 還是你能給我參考你下的 訓練指令?
> > > > 我必須使用darknet C語言版的 torch測試通過了
> > > > 萬分感謝 求指教
> > > 
> > > 
> > > 我用的这个，这个模型和网络是我自己魔改的
> > > ./darknet detector train ./data/face.data ./cfg/yolov3_face.cfg ./backup/yolov3_face_3000.weights -dont_show
> > 
> > 
> > 不好意思
> > 您的yolov3_face_3000.weights 是如何得來的呢?
> > 如果是第一次重頭訓練的話
> 
> 我记得好像是在作者的model上微调训练的，然后中间中断过，后续就在这个模型的基础上继续训练微调的

理解, 那您的cfg/yolov3_face.cfg  裡面,跟作者  mbv2_yolov3_face.cfg 內容是一樣的嗎?
如果不一樣能借參考嗎

**Comment by yjhuasheng** [comment]
> > > > > > > How did you train successfully?
> > > > > > 
> > > > > > 
> > > > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > > > 
> > > > > 
> > > > > 我編譯過了
> > > > > 但是我沒有預訓練檔案來做訓練
> > > > > 官方的是 yolov3 使用的darknet53.conv
> > > > > 這邊是用哪一個呢?
> > > > > 還是你能給我參考你下的 訓練指令?
> > > > > 我必須使用darknet C語言版的 torch測試通過了
> > > > > 萬分感謝 求指教
> > > > 
> > > > 
> > > > 我用的这个，这个模型和网络是我自己魔改的
> > > > ./darknet detector train ./data/face.data ./cfg/yolov3_face.cfg ./backup/yolov3_face_3000.weights -dont_show
> > > 
> > > 
> > > 不好意思
> > > 您的yolov3_face_3000.weights 是如何得來的呢?
> > > 如果是第一次重頭訓練的話
> > 
> > 
> > 我记得好像是在作者的model上微调训练的，然后中间中断过，后续就在这个模型的基础上继续训练微调的
> 
> 理解, 那您的cfg/yolov3_face.cfg 裡面,跟作者 mbv2_yolov3_face.cfg 內容是一樣的嗎?
> 如果不一樣能借參考嗎

最好是一样的啊，或者你就用你自己的网络重头练

**Comment by w840401** [comment]
> > > > > > > > How did you train successfully?
> > > > > > > 
> > > > > > > 
> > > > > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > > > > 
> > > > > > 
> > > > > > 我編譯過了
> > > > > > 但是我沒有預訓練檔案來做訓練
> > > > > > 官方的是 yolov3 使用的darknet53.conv
> > > > > > 這邊是用哪一個呢?
> > > > > > 還是你能給我參考你下的 訓練指令?
> > > > > > 我必須使用darknet C語言版的 torch測試通過了
> > > > > > 萬分感謝 求指教
> > > > > 
> > > > > 
> > > > > 我用的这个，这个模型和网络是我自己魔改的
> > > > > ./darknet detector train ./data/face.data ./cfg/yolov3_face.cfg ./backup/yolov3_face_3000.weights -dont_show
> > > > 
> > > > 
> > > > 不好意思
> > > > 您的yolov3_face_3000.weights 是如何得來的呢?
> > > > 如果是第一次重頭訓練的話
> > > 
> > > 
> > > 我记得好像是在作者的model上微调训练的，然后中间中断过，后续就在这个模型的基础上继续训练微调的
> > 
> > 
> > 理解, 那您的cfg/yolov3_face.cfg 裡面,跟作者 mbv2_yolov3_face.cfg 內容是一樣的嗎?
> > 如果不一樣能借參考嗎
> 
> 最好是一样的啊，或者你就用你自己的网络重头练

![S__11190323](https://user-images.githubusercontent.com/26362017/129507989-00173f08-5155-49f9-b096-18a85fa59552.jpg)
我目前用 ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg
照著作者的  訓練兩天後如圖
感覺就是個錯的樣子....

**Comment by yjhuasheng** [comment]
> > > > > > > > > How did you train successfully?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > > > > > 
> > > > > > > 
> > > > > > > 我編譯過了
> > > > > > > 但是我沒有預訓練檔案來做訓練
> > > > > > > 官方的是 yolov3 使用的darknet53.conv
> > > > > > > 這邊是用哪一個呢?
> > > > > > > 還是你能給我參考你下的 訓練指令?
> > > > > > > 我必須使用darknet C語言版的 torch測試通過了
> > > > > > > 萬分感謝 求指教
> > > > > > 
> > > > > > 
> > > > > > 我用的这个，这个模型和网络是我自己魔改的
> > > > > > ./darknet detector train ./data/face.data ./cfg/yolov3_face.cfg ./backup/yolov3_face_3000.weights -dont_show
> > > > > 
> > > > > 
> > > > > 不好意思
> > > > > 您的yolov3_face_3000.weights 是如何得來的呢?
> > > > > 如果是第一次重頭訓練的話
> > > > 
> > > > 
> > > > 我记得好像是在作者的model上微调训练的，然后中间中断过，后续就在这个模型的基础上继续训练微调的
> > > 
> > > 
> > > 理解, 那您的cfg/yolov3_face.cfg 裡面,跟作者 mbv2_yolov3_face.cfg 內容是一樣的嗎?
> > > 如果不一樣能借參考嗎
> > 
> > 
> > 最好是一样的啊，或者你就用你自己的网络重头练
> 
> ![S__11190323](https://user-images.githubusercontent.com/26362017/129507989-00173f08-5155-49f9-b096-18a85fa59552.jpg)
> 我目前用 ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg
> 照著作者的 訓練兩天後如圖
> 感覺就是個錯的樣子....

那就测一批图像的结果看看模型啊，我测过作者的模型，没啥问题啊

**Comment by w840401** [comment]
> > > > > > > > > > How did you train successfully?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 只要编译通过，训练的话应该没问题的啊，不过还是用大佬的torch版本的吧，更简单
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我編譯過了
> > > > > > > > 但是我沒有預訓練檔案來做訓練
> > > > > > > > 官方的是 yolov3 使用的darknet53.conv
> > > > > > > > 這邊是用哪一個呢?
> > > > > > > > 還是你能給我參考你下的 訓練指令?
> > > > > > > > 我必須使用darknet C語言版的 torch測試通過了
> > > > > > > > 萬分感謝 求指教
> > > > > > > 
> > > > > > > 
> > > > > > > 我用的这个，这个模型和网络是我自己魔改的
> > > > > > > ./darknet detector train ./data/face.data ./cfg/yolov3_face.cfg ./backup/yolov3_face_3000.weights -dont_show
> > > > > > 
> > > > > > 
> > > > > > 不好意思
> > > > > > 您的yolov3_face_3000.weights 是如何得來的呢?
> > > > > > 如果是第一次重頭訓練的話
> > > > > 
> > > > > 
> > > > > 我记得好像是在作者的model上微调训练的，然后中间中断过，后续就在这个模型的基础上继续训练微调的
> > > > 
> > > > 
> > > > 理解, 那您的cfg/yolov3_face.cfg 裡面,跟作者 mbv2_yolov3_face.cfg 內容是一樣的嗎?
> > > > 如果不一樣能借參考嗎
> > > 
> > > 
> > > 最好是一样的啊，或者你就用你自己的网络重头练
> > 
> > 
> > ![S__11190323](https://user-images.githubusercontent.com/26362017/129507989-00173f08-5155-49f9-b096-18a85fa59552.jpg)
> > 我目前用 ./darknet detector train data/face.data cfg/mbv2_yolov3_face.cfg
> > 照著作者的 訓練兩天後如圖
> > 感覺就是個錯的樣子....
> 
> 那就测一批图像的结果看看模型啊，我测过作者的模型，没啥问题啊

摁摁我還沒測自己的
也測過作者的模型 沒啥問題
只是很不太知道 到底怎訓練出來的....只能等一下了
