### ISSUE TITLE
the test speed

### ISSUE THREAD

**Issue by zyg11** [ouyanghuiyu/darknet_face_with_landmark#4]
Good job!I wonder the test speed.Could you provide the test speed in gpu or cpu environment?Thank you!

**Comment by deep-practice** [comment]
2080ti 608x608输入
./test_imgs/input/selfie.jpg: Predicted in 6.259000 milli-seconds.

**Comment by nikkymen** [comment]
I got the following results:
TensorRT 7.0, GTX 1070, 608x608, median time: 6.4045 ms (156 FPS), 413 MB GPU memory used
